import React, { useEffect } from "react";
import Button from "@material-ui/core/Button";

var collections = [
  {
    canister: "zejmq-rqaaa-aaaah-qcnsq-cai",
    priority : 10,
    name: "Elementum: Interitus",
    brief : "New spells and instant cards",
    description : "Change the flow of a match with the new Interitus collection, there's an option for every playstyle!",
    keywords : "Games Elementum Interitus Faceted Meninas",
    banner : "/collections/interitus/banner.jpg",
    avatar : "/collections/interitus/avatar.jpg",
    collection : "/collections/interitus/collection.jpg",
    telegram : "https://t.me/a3capaschat",
    discord : "https://discord.gg/Vses99CepK",
    twitter : "https://twitter.com/a3capas",
    medium : "https://elementum.medium.com",
    web : "https://universo.a3capas.com",
    route: "interitus",
    unit : "NFT",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "822d0a778eb558db58f12adc0be99c6352bad19dbc7c3b31919c3ac3adad8c82",
    blurb: (<><p>Elementum proudly releases its second collection: Interitus. These new pieces will definitely give you an edge in our upcoming first risky game and in 2022 they'll function as our instant cards for our Trading Card Game, spells that can change the conditions of match and let you walk away victorious. For more information, join The Agora on Discord. We can't thank you enough for all your support. Welcome aboard!</p></>),
  },
  {
    canister: "z7mqv-liaaa-aaaah-qcnqa-cai",
    priority : 10,
    name: "ICircle - Pythagoras",
    brief : "2222 ICircle Generative Art NFT 1st Collections",
    description : "ICircle is created by combining mathematics, creative coding, and aesthetic soul, which results in beautiful arts. ICircle has the power to uplift a fresh vibe into your NFT collections",
    keywords : "Generative Art Mathematics NFT",
    banner : "/collections/icircle/banner.png",
    avatar : "/collections/icircle/avatar.jpg",
    collection : "/collections/icircle/collection.jpg",
    //telegram : "https://t.me/icpets",
    discord : "https://discord.io/ICircle_NFT",
    twitter : "https://twitter.com/icircle_nft",
    //medium : "https://medium.com/@ICPrime8s",
    web : "https://icircle.gallery/",
    route: "icircle",
    unit : "NFT",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "332b97f5d5425b72d6058b17df99714f338055299dbb7a855a7432a785f178cf",
    blurb: (<><p>ICircle NFT is a generative art created by combining mathematics, creative coding, and aesthetic soul, which results in beautiful art. ICircle is formed by mathematical functions and applied geometry.</p><p>"Circle" (as part of the name) is used not only because it is related to mathematics and geometry, but also because circle plays an important role in this artwork. It's DNA because If you zoom in very closely into our art, you'll see that millions of circles build up into a masterpiece.</p><p>The best part about ICircles Artwork is that it instills a fresh vibe into its aesthetic. ICircle has the power to uplift the vibe of a place and make it look simply beautiful. ICircle Art can also encourage us to be more creative, sparking new ideas and helping us process both real and metaverse parts of our lives by only looking, holding, and interpreting them.</p></>),
  },
  // {
    // canister: "5367t-oaaaa-aaaah-qcnlq-cai",
    // priority : 10,
    // name: "FlokiCyberPunk",
    // brief : "Farm ICP in the game FlokiCyberPunk!",
    // description : "NFT owners will be able to earn x2, x5, x10 times more tokens in Internet Computer (ICP) game than everyone else!",
    // keywords : "GameFi NFT",
    // banner : "/collections/floki/banner.png",
    // avatar : "/collections/floki/avatar.jpg",
    // collection : "/collections/floki/collection.png",
    // //telegram : "https://t.me/icpets",
    // discord : "https://discord.com/invite/ytypDeM2Fv",
    // twitter : "https://twitter.com/flokicyberpunk",
    // //medium : "https://medium.com/@ICPrime8s",
    // web : "https://flokicyberpunk.com/",
    // route: "flokicyberpunk",
    // unit : "Floki",
    // nftv : false,
    // mature: false,
    // market : true,
    // commission: 0.11,
    // comaddress: "a1e0ae5c0fe809215a46e82b08ceb4b437dbe5e84c7480335252427e365bf3a2",
    // blurb: (<><p>Total 4500 NFT FlokiCyberpunk in Internet Computer (ICP).</p>
// <p>Play and earn ICP tokens depending on your NFT, the priority in the game will be<br />
// Common (no zeros) - x2 priority,<br />
// Rare (one zero) - x3 priority,<br />
// Super Rare (two zeros) - x5 priority,<br />
// Legendary (three zeros) - x7 priority,<br />
// Unique - (four zeros) x10 priority</p>
// <p>But even if you buy and you come across a Common, you will still have advantages over other players who do not have NFT FlokiCyberPunk!</p><p>The owners of NFT FlokiCyberPunk will have a special avatar armor, all other NFT owners will not have such armor!
// Therefore, the owners of NFT FlokiCyberPunk can earn 2-10 times more than all other users.</p></>),
  // },
  {
    canister: "4kubm-wiaaa-aaaah-qcnoa-cai",
    priority : 10,
    name: "TheSwordNFT - Ninjas",
    brief : "10k Unique Ninjas from TheSwordNFT",
    description : "This collection was designed with the intent of game/metaverse intergration in the future.",
    keywords : "Utility Game Metaverse Miniverse RPG",
    banner : "/collections/sword/banner.png",
    avatar : "/collections/sword/avatar.jpg",
    collection : "/collections/sword/collection.jpg",
    //telegram : "https://t.me/icpets",
    discord : "https://discord.gg/Xgc5zTrdSb",
    twitter : "https://twitter.com/TheSwordNft",
    //medium : "https://medium.com/@ICPrime8s",
    web : "http://TheSwordNFT.com",
    route: "sword",
    unit : "SwordNFT",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "0389f1b21ce2f0aa73502b2be4625969b928eff002e2ff39161b50a98c18fbcd",
    blurb: (<><p>TheSwordNFT is a collection of Warriors and Guardians. The first series from the Warriors collection is Ninjas. These characters are designed to be a part of balanced game in which the NFT attributes play a role in game mechanics. There are 14 weapons, 3 skins, and 4 environments to choose from. If you are able to collect all 4 environments(backgrounds), there will be benefits inside the game and outside of the game.</p><p>Guardians, which will be introduced later, serve the purpose of protecting the warriors in battle. They will also have fun perks in the metaverse. Holders of the Ninja collection will be eligible for presale & drops of future collections.</p></>),
  },
  {
    canister: "5h2fc-zaaaa-aaaah-qcnjq-cai",
    priority : 10,
    name: "ICPrime8s",
    brief : "5 releases of randomly generated Prime8 NFTs",
    description : "Welcome to the Jungle! We've got plans in place to make ICPrime8s one of the best NFT collections on the IC. Stay tuned for more updates!",
    keywords : "2D PFP NFT",
    banner : "/collections/prime8s/banner.jpg",
    avatar : "/collections/prime8s/avatar.png",
    collection : "/collections/prime8s/collection.jpg",
    //telegram : "https://t.me/icpets",
    discord : "https://discord.gg/3rxhVdBk6Z",
    twitter : "https://twitter.com/ICPrime8s",
    medium : "https://medium.com/@ICPrime8s",
    web : "http://cprime8s.com",
    route: "prime8s",
    unit : "Prime8s",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "a4593dfd6aa5c44c0af59e26935d607dea1f9007ddb83a56180df7e499adf13a",
    blurb: (<><p>For nearly 60 million years Prime8s have roamed the earth and now they're coming to the Internet Computer! ICPrime8s is a collection of 10,500 (total) NFTs and will be released as 5 seperate releases. Following the evolutionary timeline of Prime8s, each release will depict a different Prime8 unique with its own traits and characteristics.</p></>),
  },
  {
    canister: "v3zkd-syaaa-aaaah-qcm5a-cai",
    priority : 10,
    name: "IC Kitties",
    brief : "10,000 8-bit Kitties",
    description : "Get into the Kittyverse by joining one of the 7 Kingdoms of our world and discover the beautiful wonders waiting inside.",
    keywords : "ickitties kitties cats kittens",
    banner : "/collections/ickitties/banner.png",
    avatar : "/collections/ickitties/avatar.jpg",
    collection : "/collections/ickitties/collection.jpg",
    //telegram : "https://t.me/icpets",
    discord : "https://discord.gg/r2c4TTr4un",
    twitter : "https://twitter.com/ICKitties",
    //medium : "https://medium.com/@icpets01/introducing-icpets-the-hold-2-earn-nft-on-the-ic-ecosystem-8111c1550caf",
    web : "https://www.ickitties.com/",
    route: "ickitties",
    unit : "IC Kitty",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "cb69faae15474a224a9d600d2b92128f2190dc62aad0059f20886727bacd4913",
    blurb: (<><p>The story of ICKitties happens nowadays, in a busy city street, where kitties live peacefully. One of the kitties - Zack - walks on the sidewalk minding his own business, when all of a sudden a book drops from a window and opens in front of him.</p><p>Zack goes through the book and he finds the answer to a question that he always had - "Why are there different colored kitties? Why aren’t we all the same?"</p><p>As soon as he finds the answer, he runs to a dark alley and gathers all his friends to tell them about the long forgotten 7 kitty Kingdoms and how each kitty comes from one of the Kingdoms, ruled by 7 kings and 7 queens, and overseen by 7 gods. What Kingdom will you choose?</p></>),
  },
  {
    canister: "unssi-hiaaa-aaaah-qcmya-cai",
    priority : 10,
    name: "ICPets",
    brief : "11,111 unique pets (Hamster, Penguin & Racccoon)",
    description : "Community Revenue Focused NFT Project. ICPets is a Hold-2-Earn lifestyle aimed to increase your earnings through passive income and to build a strong community around art and financial opportunities by using NFT technology and its smart contracts power.",
    keywords : "P2E, pets, icpets, rewards, airdrop, royalties",
    banner : "/collections/icpets/banner.png",
    avatar : "/collections/icpets/avatar.jpg",
    collection : "/collections/icpets/collection.png",
    telegram : "https://t.me/icpets",
    discord : "https://discord.gg/MvWznssB",
    twitter : "https://twitter.com/icpets",
    medium : "https://medium.com/@icpets01/introducing-icpets-the-hold-2-earn-nft-on-the-ic-ecosystem-8111c1550caf",
    web : "https://icpets.io",
    route: "icpets",
    unit : "IC Pet",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "222f75cac912282d33a8ef2a396e409464b4a57ec9e347264f4952473fa3d983",
    blurb: (<><p>ICPets are 11,111 unique beautifully designed and well-crafted pets each having its unique abilities and superpowers. They don't want to be ordinary animals anymore; they are looking forward to entering the metaverse and bringing their owners more profit! Join the Pets Gang today and get a chance to adopt your pet today (little friend!) They are waiting for you!.</p><p>ICpets NFTs is your access to Holders Rewards ?lub. NFT is not just a cute picture, our main goal is to bring value to each of ICPets Holders and to the Ecosystem itself. We are convinced that NFT collection success depends on its community strength. Mutual development and growth are possible when art collection is backed up by strong financial incentives. Therefore, we spent lots of time developing the economic aspects of the project – the unique motivation and rewards system.</p></>),
  },
  {
    canister: "xphpx-xyaaa-aaaah-qcmta-cai",
    priority : 10,
    name: "CYMAN",
    brief : "7,777 randomly generated cybernetic humanoids",
    description : "CYMAN is a collection initially composed of 7,777 fully deconstructable NFTs. CYMAN is an evolving metaversal project with the goal to span out into real world activations, brand partnerships, event ticketing and gaming collaborations.",
    keywords : "Utility Gamefi Staking",
    banner : "/collections/cyman/banner.jpg",
    avatar : "/collections/cyman/avatar.jpg",
    collection : "/collections/cyman/collection.jpg",
    discord : "https://discord.gg/cyman",
    twitter : "https://twitter.com/cyman_live",
    web : "https://www.cyman.live/",
    route: "cyman",
    unit : "CYMAN",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "e4d20c3d0cfb3c62be55414af7314ab9535348ea45118471e965e39d81ee6330",
    blurb: (<><p>Welcome to CYMAN. Lead artist Brad Donovan has teamed up with Dfinity's own Arthur Falls, Toniq Labs, and creative studio Vesica Aotearoa to create a universe of cybernetic humanoids called CYMAN from 550BC. This project is composed of 7,777 CYMEN that will be deconstructable and eventually fully customisable. The core utility of the NFT will be as an access token for CYMAN-exclusive online media, real-world events, and gaming collaborations.</p><p>Gen0 CYMEN will be breedable as the project grows we will introduce more characters and developments into the CYMAN story that will add value to the original CYMEN.</p></>),
  },
  {
    canister: "txr2a-fqaaa-aaaah-qcmkq-cai",
    priority : 10,
    name: "Meme Cake",
    brief : "7,777 Dick NFT's",
    description : "Meme Cake is a Social NFT marketplace.",
    keywords : "Marketplace, Meme, Social, NFT",
    banner : "/collections/mc/banner.jpg",
    avatar : "/collections/mc/avatar.png",
    collection : "/collections/mc/collection.jpg",
    telegram : "https://t.me/meme_cake",
    discord : "https://discord.com/invite/3CrSxgccPM",
    twitter : "https://twitter.com/realmemecake",
    web : "https://memecake.io/",
    route: "memecake",
    unit : "DICK",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "2b07d34e254e077e0ef01b1784fcd790016057781e67dbdccc59217ccad725fb",
    blurb: (<><p>Meme Cake is a Social NFT marketplace. This is a marketplace where you can SHILL and SELL your NFT's. The community can vote on the best projects and fund them and help them launch.</p></>),
  },
  {
    canister: "xzxhy-oiaaa-aaaah-qclnq-cai",
    priority : 10,
    name: "YOLO Octopus",
    brief : "8888 Octopi with YOLO lifestyle",
    description : "'You Only Live Once' - No NFTs will sit idle. Amazing tools where u can create animation, add music & enter DIGITAL STUDIO. 3D collection will also be launched soon.",
    keywords : "#YoloOctopus #YoloClubToken #Metaverse #YoloTools #Yolo3D",
    banner : "/collections/yolo/banner.jpg",
    avatar : "/collections/yolo/avatar.jpg",
    collection : "/collections/yolo/collection.jpg",
    discord : "https://discord.gg/GqvD72BnCH",
    twitter : "https://twitter.com/EnterYoloClub",
    web : "https://enteryoloclub.com/",
    route: "yolo-octopus",
    unit : "NFT",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "3610ebfa5e29be650360e20fa93622625cdddcda7b45902f160f33cfcd1ea3c1",
    blurb: (<><p>YOLO pass launch in Q1 2022 in which you are eligible for 1. future airdrops 2. Free to use tools - Build, animate, add music and much more 3. Enter pre-mint stage for future collections 4. Limited edition merchandise 5. Free entry to digital STUDIO ?In Q1 2022 : Integration of characters in our Gaming world which is based on the concept of Play to Earn with Real Time Al generated wearables and collectibles?In Q2 2022 our land sales will begin for our metaverse backed by YOLO token.</p></>),
  },
  {
    canister: "t2eok-gyaaa-aaaah-qclwq-cai",
    priority : 10,
    name: "Tranquillity",
    brief : "99 Hand-Crafted Pastel Paintings",
    description : "The Tranquillity Collection is the first collection released by ICP Art - it is also a governing collection over the ART DAO.",
    keywords : "ART DAO GOVERNANCE",
    banner : "/collections/tranquillity/avatar.jpg",
    avatar : "/collections/tranquillity/avatar.jpg",
    collection : "/collections/tranquillity/avatar.jpg",
    discord : "https://discord.gg/pgaXM88PgQ",
    twitter : "https://twitter.com/ICP_Art",
    telegram : "https://t.me/TheICPArt",
    route: "tranquillity",
    unit : "Painting",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "2975800b3ff4ad824bdf559793c3b2bedbbdfb2350fc32d29e0274e3faa6626a",
    blurb: (<><p>The Tranquility Collection is the first collection released by ICP Art. It is a set of 99 Hand-Crafted 1 of 1 Pastel Paintings, that governs the ART DAO.
The ART DAO is a platform that allows the user to contribute to the creative process of creating NFTs, and decide the type of artwork they'd like to see in the ecosystem.</p></>),
  },
  {
    canister: "zvycl-fyaaa-aaaah-qckmq-cai",
    priority : 10,
    name: "ICApes",
    brief : "Dfinity's First Ape NFT Collection",
    description : "10,000 Unique Apes of Internet Computer. IC Apes are ready to take over the ecosystem.",
    keywords : "ICApes, Ape NFT, IC Ape Ventures",
    banner : "/collections/icapes/banner.jpg",
    avatar : "/collections/icapes/avatar.jpg",
    collection : "/collections/icapes/collection.jpg",
    medium : "https://medium.com/@icapeventures",
    discord : "https://discord.com/invite/icapeventures",
    twitter : "https://twitter.com/ICApe_Ventures",
    web : "https://icapeventures.com/",
    route: "icapes",
    unit : "Ape",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "598b376d9ddc5d3df21dcac0f888a7c898437a310d477d040e9b40457e3e2d35",
    blurb: (<><p>IC Apes represent a collection of 10,000 apes. The Apes are stored on-chain in the Internet Computer. It’s the first generated Ape NFT collection for the ICP.</p><p>We make sure that every emerging product looks realistic, charismatic, strong and intelligent. We have worked for be more detailed and more realistic than alternatives in the market.</p><p>Our goal is to create a IC Ape Starter as a leading launchpad for the Internet Computer ecosystem. Also as a IC Ape Ventures, funding the innovative projects on the Internet Computer.</p></>),
  },
  {
    canister: "3ifmd-wqaaa-aaaah-qckda-cai",
    priority : 10,
    name: "ICSnakes",
    brief : "A collection of 10,000 randomly generated snake",
    description : "First NFT with built-in mini-game! A collection of 10,000 randomly generated NFTs on the Internet Computer hunting for food.",
    keywords : "Mini-game Snakes",
    banner : "/collections/icsnakes/banner.jpg",
    avatar : "/collections/icsnakes/avatar.jpg",
    collection : "/collections/icsnakes/collection.jpg",
    discord : "https://discord.com/invite/H9YUpwVrkQ",
    twitter : "https://twitter.com/ICSnakes",
    web : "https://xn--4n8h7h.ws/",
    route: "icsnakes",
    unit : "ICSnake",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "05860acf5b5478588e90557507d8c9c26dcff03289075c450d2dc39c6da39c28",
    blurb: (<><p>We're bringing the first interactive &#128013; NFTs to the Internet Computer! Our NFTs are not just art to show off to other collectors and appreciate, they offer an interactive experience where you can actually play with and enjoy your &#128013; NFT in a whole new way. Every NFT image will have a mini-game built-in and is a unique avatar in the multiplayer game which is currently under development.</p></>),
  },
  {
    canister: "px5ub-qqaaa-aaaah-qcjxa-cai",
    priority : 10,
    name: "Imagination Project",
    brief : "400 Years on Human Innovation",
    description : "The Imagination Project, created 50 photographs over the course of a year, celebrating the human imagination in all its wild and vast diversity. Visualising 400 years of groundbreaking Patents.",
    keywords : "The Imagination Project, Innovation, StudioTedd, conceptual photography, still life photography",
    banner : "/collections/imagination/banner.jpg",
    avatar : "/collections/imagination/avatar.jpg",
    collection : "/collections/imagination/collection.jpg",
    discord : "https://discord.com/invite/CSrZck25st",
    twitter : "https://twitter.com/StudioTedd",
    web : "https://www.icphotographers.com/",
    route: "imagination",
    unit : "NFT",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "ace16992dcde53c7c67b396b65924be0e19bed8704a2a68b9cc794d100c3cd17",
    blurb: (<><p>A photographer who brings a sense of underlying magic to the meticulous conceptual images he creates.</p><p>Bringing his attentive eye and deep relationship with nature into the built studio environment, Ted's still life images are anything but static, as every photograph is infused with a sense of action or motion.</p><p>A true polymath who works across a number of sectors, Ted is adept at bringing together teams of scientists, model-builders, engineers, doctors, mathematicians, sculptors, set designers and artists to create engaging imagery for his international clientele and personal projects.</p><p>Ted's recent work with The Royal Academy of Engineering has exhibited at The National Science and Media Museum (UK) and Edinburgh Science Festival (UK)</p><p>The Imagination Project, created 50 photographs over the course of a year, celebrating the human imagination in all its wild and vast diversity.  The Projects narrative is formed through the interpretation of 400 years of Patents. A veritable encyclopaedia of human achievement.</p></>),
  },
  {
    canister: "bzsui-sqaaa-aaaah-qce2a-cai",
    priority : 101,
    name: "Poked bots",
    brief : "10,000 generated mutant Robots",
    description : "500 years from now humans have left earth and only the Robots remain. Robots have managed to create new identities based on relics they have found from earths past",
    keywords : "pokedstudio robot NFT dfinty icp collectable Solana etherium trade crypto market ",
    banner : "/collections/poked/banner.jpg",
    avatar : "/collections/poked/avatar.jpg",
    collection : "/collections/poked/collection.jpg",
    discord : "https://discord.gg/PokedStudioNFT",
    twitter : "https://twitter.com/pokedstudiouk",
    web : "https://www.pokedstudiobotsnft.co.uk",
    route: "poked",
    unit : "Bot",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "ace16992dcde53c7c67b396b65924be0e19bed8704a2a68b9cc794d100c3cd17",
    blurb: (<><p>500 years from now humans have long left earth and only the Robots remain. Robots have managed to create new identities often based on relics they have found from earths past. This collection features 5 groups of Robots that exist in the eastern waste lands near former Delta city. The Battle bots, they are tough and are used to hard work, entertainment bots constructed from old video game and junk food toy parts found in the giant rubbish heaps of former Antarctica. Wild bots have become deranged after the giant solar flare of 2453AD. The god class has come to rule much of eastern earth, they have abilities beyond normal bots. The masters are a secret society of robots that have links to the off world colony of Europa base 7.</p></>),
  },
  {
    canister: "poyn6-dyaaa-aaaah-qcfzq-cai",
    priority : 10,
    name: "Blockchain Heroes",
    unit : "Card",
    brief : "50 original heroes in 6 variations",
    description : "Be a part of blockchain history as the first ICP launch featuring packs of cards comes your way in the form of the best-selling Blockchain Heroes! Collect all 50 heroes in six unique variations!",
    keywords : "heroes cards collecting",
    banner : "/collections/bh/banner.png",
    avatar : "/collections/bh/avatar.png",
    collection : "/collections/bh/collection.jpg",
    discord : "https://discord.gg/herohq",
    twitter : "https://twitter.com/bc_heroes",
    web : "http://bcheroes.com",
    route: "blockchain-heroes",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "9e4c5a298aa65baf99cbf4056f443b2c499d4c6d07f4030c5474885f6803d9d0",
    blurb: (<><p>Entrepot is thrilled to welcome the best-selling Blockchain Heroes series to the Internet Computer! Originally presented on the WAX blockchain in Summer of 2020, Blockchain Heroes is a set of 50 super heroes inspired by real-world blockchain and crypto personalities. When the initial set was offered in August 2020, 12500 packs sold out in just 20 minutes! Since that time, the team has released two additional series, with the latter selling out in just 35 seconds.</p>
<p>Now we are pleased to issue the original 50 heroes on ICP with all NEW variations. 5000 packs are being made available, with each pack containing five (5) random hero cards from the set. Each of the fifty heroes is available in common, uncommon, rare, epic, legendary and mythic variations, with odds of getting variations decreasing as the rarity increases. Packs will be made available at 10 am EST on November 12th for just 1.5 ICP! If previous sales of Blockchain Heroes are any indication, we expect this sale to go very fast. So be locked and loaded with your ICP to grab yours.</p>
<p>Will you get an epic Captain Crypto, a legendary Lady Lightning or the elusive mythic Genesis? Grab your packs and rip them open to find out!
</p><p><strong>Read more about the IC-unique Sir Singularity hero and how to get it <a target="_blank" href="https://toniqlabs.medium.com/blockchain-heroes-sir-singularity-release-ce1b3a285fd9">here</a>!</strong></p></>),
  },
  {
    canister: "dylar-wyaaa-aaaah-qcexq-cai",
    priority : 10,
    name: "Flight",
    unit : "Image",
    brief : "Wing takes flight",
    description : "Wing embodies the feeling of freedom",
    keywords : "#photography #movement # #dance #freedom #ICPhotographer",
    banner : "/collections/flight/banner.jpg",
    avatar : "/collections/flight/avatar.jpg",
    collection : "/collections/flight/collection.jpg",
    discord : "https://discord.com/invite/CSrZck25st",
    twitter : "https://twitter.com/olisav",
    web : "https://www.icphotographers.com/",
    route: "flight",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "4dbdfc6d6bdab7851bfc7839da5c3df06d10f89ab61cf0c136b70812da27d608",
    blurb: (<>Rare are the moments when technology so drastically emprove the lives of so many.
We are living through something profoundly special, and as an artist, I have never felt
so free. This piece is dedicated to all those that helped me find myself here.</>),
  },
  {
    canister: "ag2h7-riaaa-aaaah-qce6q-cai",
    priority : 10,
    name: "P2J",
    unit : "Track",
    brief : "NFT by Canistore",
    description : "P2J NFT by Canistore",
    keywords : "bulls dfinity",
    banner : "/collections/p2j/banner.png",
    avatar : "/collections/p2j/avatar.png",
    collection : "/collections/p2j/collection.png",
    twitter : "https://twitter.com/canistore",
    //discord : "https://discord.gg/mA5cXdAtwe",
    //web : "https://www.infernalvampires.com",
    route: "p2j",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "1139e8bf919647a9e630f41982324ea535ccd67ac4b101644bb1dba8ecf155e3",
    blurb: (<><p>P2J NFT by Canistore</p></>),
  },
  {
    canister: "dknxi-2iaaa-aaaah-qceuq-cai",
    priority : 10,
    name: "Dfinity Bulls",
    unit : "Bull",
    brief : "8,888 Badass Bulls of the IC",
    description : "The Bulls of the IC -P2E game coming soon",
    keywords : "bulls dfinity GameFi",
    banner : "/collections/bulls/banner.png",
    avatar : "/collections/bulls/avatar.png",
    collection : "/collections/bulls/collection.png",
    discord : "https://discord.gg/GBSNhYeGxh",
    twitter : "https://twitter.com/DBulls_NFT",
    web : "https://twitter.com/DBulls_NFT",
    route: "dfinitybulls",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "ae5cf8b282013bffd28908f1c4afad389a07e474a02f9a8e48bcc07cc63b05b4",
    blurb: (<><p>8,888 Badass Bulls of the IC . Our NFT is not only just a collectible art but with utility too! We will be coming out with a P2E battle arena game with toniqlabs ! Stay tuned!</p></>),
  },
  {
    canister: "gyuaf-kqaaa-aaaah-qceka-cai",
    priority : 10,
    name: "Infernal Vampire Colony",
    unit : "Vampire",
    brief : "666 Bloodthirsty Infernal Vampires",
    description : "Infernal Vampires had been in the lair for a long time. They finally managed to get out. Time for them to suck some blood!",
    keywords : "Vampire, Vampires, Infernal, Colony, Blood, Bloodthirsty, 666, Lair",
    banner : "/collections/ivc/banner.jpg",
    avatar : "/collections/ivc/avatar.png",
    collection : "/collections/ivc/collection.jpg",
    discord : "https://discord.gg/mA5cXdAtwe",
    twitter : "https://twitter.com/IVCNFT",
    web : "https://www.infernalvampires.com",
    route: "ivc",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "7243722b9db43a26170b2bbc065b02f5ca2d1836ddaaee5ef05fc043a01f9ed9",
    blurb: (<><p>Infernal Vampires had been in the lair for a long time. They finally managed to get out. Time for them to suck some blood!</p></>),
  },
  {
    canister: "oeee4-qaaaa-aaaak-qaaeq-cai",
    priority : 10000,
    brief : "10,000 Motokos dropped by DFINITY",
    name: "Motoko Day Drop",
    unit : "Motoko",
    keywords : "",
    banner : "/banner/motoko2.jpg",
    discord : "https://t.co/fD0VHKGaFu?amp=1",
    twitter : "https://twitter.com/pokedstudiouk",
    route: "motoko",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "09b739076e074550862930ca17f662485076a6af60cc1b0e9a1f50b058d767c9",
    blurb: (<><p>On the Motoko programming language's 2nd birthday, the DFINITY Foundation distributed 10,000 Motoko ghosts designed by Jon Ball of Pokedstudios to the community.</p></>),
  },
  {
    canister: "er7d4-6iaaa-aaaaj-qac2q-cai",
    priority : 10,
    name: "MoonWalkers",
    unit : "Moonwalker",
    brief : "9999 3D MoonWalkers by IC Gallery",
    route: "moonwalkers",
    keywords : "",
    banner : "/banner/icgallery2.jpg",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.05,
    comaddress: "2455059d792289741fb4c3128be9dfcf25474e161923c78c37bd53c457b24e60",
    blurb: (<><p>The MoonWalker's marketplace will open after the completion of the <a href="/sale/moonwalkers">public sale</a>.</p></>),
  },
  {
    canister: "e3izy-jiaaa-aaaah-qacbq-cai",
    priority : 1000,
    name: "Cronic Critters",
    unit : "Cronic",
    brief : "The first IC NFT by Toniq",
    route: "cronics",
    banner:"https://cronic.toniqlabs.com/banner.png",
    twitter:"https://twitter.com/CronicsP2E",
    telegram:"https://t.me/cronic_talk",
    medium:"https://toniqlabs.medium.com/cronics-breeding-and-supply-604fa374776d",
    keywords : "",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.025,
    comaddress:"c7e461041c0c5800a56b64bb7cefc247abc0bbbb99bd46ff71c64e92d9f5c2f9",
    blurb: (<>Cronics is a Play-to-earn NFT game being developed by ToniqLabs for the Internet Computer. Cronics incorporates breeding mechanics, wearable NFTs and a p2e minigame ecosystem and more.</>),
  },

  {
    canister: "pnpu4-3aaaa-aaaah-qcceq-cai",
    priority : 10,
    name: "Infinite Chimps",
    unit : "Chimp",
    brief : "A collaboration of goodness",
    route: "infinite-chimps",
    keywords : "",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "90d2fd9f8c4005da2ebf73579a4f571763d21ce35ed4c32e83b3158cb68c7c45",
    blurb: (<p>100% of initial sales proceeds and 3% of resales go to Chimpanzee Sanctuary Northwest. The sanctuary provides a 'forever home' for chimpanzees discarded from the entertainment and biomedical testing industries. Every Infinite Chimp in this NFT collection is a portrait of a rescued chimp that now lives peacefully at the sanctuary.</p>),
  },

  {
    canister: "bid2t-gyaaa-aaaah-qcdea-cai",
    priority : 10,
    name: "Haunted Hamsters",
    unit : "Hamster",
    brief : "3333 Haunted Hamsters ready to spook",
    route: "hauntedhamsters",
    banner : "/collections/hh/banner.jpg",
    avatar : "/collections/hh/avatar.jpg",
    collection : "/collections/hh/collection.jpg",
    description : "Haunted Hamsters are 3333 hamsters, who have been haunted on the hill of Hamsterville. They come merged from 10 spooky themed traits, and are now living on the ICP blockchain.",
    keywords : "",
    web : "https://www.hauntedhamsters.io",
    telegram : "https://t.me/joinchat/3KX8XkSEcREzYTMx",
    medium : "https://medium.com/@hauntedhamsters",
    discord : "https://discord.com/invite/rngMQQxa",
    twitter : "https://twitter.com/hauntedhamsters",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "35b902472e845179b3d6ad9ff7079fee6bcadb4e0ca870230ba7a79757fa88fb",
    blurb: (<><p>Haunted Hamsters are 3333 hamsters, who have been haunted on the hill of Hamsterville. They come merged from 10 spooky themed traits, and are now living on the ICP blockchain.</p></>),
  },
  {
    canister: "ahl3d-xqaaa-aaaaj-qacca-cai",
    priority : 10,
    name: "ICTuTs",
    unit : "ICTuT",
    brief : "10,000 NFTs based on King TuT",
    route: "ictuts",
    banner : "/banner/ictuts.png",
    keywords : "",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.025,
    comaddress:
      "b53a735c40994ddbc7bb4f6dbfbf9b2c67052842241f1c445f2255bdf4bd8982",
    blurb: false,
  },
  {
    canister: "sr4qi-vaaaa-aaaah-qcaaq-cai",
    priority : 10,
    name: "Internet Astronauts",
    unit : "Astronaut",
    brief : "10,000 Internet Astronauts",
    description : "Internet Astronauts are collection of 10,000 end-to-end-on-chain NFT collectibles only possible through Internet Computer! Internet Astronauts are founding pass NFT’s of IC dAppverse’s.",
    route: "interastrosc",
    keywords : "Internet Astronauts IASC InternetAstronauts AstronautNFT",
    banner : "/collections/iasc/banner.png",
    avatar : "/collections/iasc/avatar.jpg",
    collection : "/collections/iasc/collection.jpg",
    discord : "https://discord.com/invite/interastrosc",
    twitter : "https://twitter.com/interastrosc",
    medium : "https://medium.com/@interastrosc",
    web : "https://interastrosc.com/",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress:
      "2be01f5e8f081c6e8784b087fb1a88dac92fdd29203c1e456a6e90950c6e6e21",
    blurb: (<>Internet Astronauts are collection of 10,000 end-to-end-on-chain NFT collectibles only possible through Internet Computer! Internet Astronauts are founding pass NFT’s of IC dAppverse’s.</>),
  },
  {
    canister: "nfvlz-jaaaa-aaaah-qcciq-cai",
    priority : 10,
    name: "IC3D",
    unit : "IC3D",
    brief : "10,000 3D Scenes made of 60,000 NFTs",
    route: "ic3d",
    keywords : "",
    banner : "/banner/ic3d.jpg",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress: "b29f5dc935f0457df12c9f91a58d77e192a0acb00694ca473d342063d375656c",
    blurb: (<><p>The IC3D marketplace will open after the completion of the <a href="/sale/ic3d">public sale</a>.</p></>),
  },
  {
    canister: "nbg4r-saaaa-aaaah-qap7a-cai",
    priority : 10,
    name: "Starverse",
    unit : "Star",
    brief : "The first free NFT airdrop",
    route: "starverse",
    keywords : "",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.025,
    comaddress:
      "c7e461041c0c5800a56b64bb7cefc247abc0bbbb99bd46ff71c64e92d9f5c2f9",
    blurb: false,
  },
  {
    canister: "njgly-uaaaa-aaaah-qb6pa-cai",
    priority : 10,
    name: "ICPuppies",
    unit : "ICPuppy",
    brief : "10,000 unique randomly generated 8-bit puppies",
    description : "ICPuppies is a randomly generated 8-bit puppy NFT collection. Half of the initial sale profits will be directed towards charities as well as a portion of all resale volume.",
    route: "icpuppies",
    keywords : "puppies icpuppies nft charity 8-bit pixel dog doge puppy",
    banner : "/collections/icpuppy/banner.jpg",
    avatar : "/collections/icpuppy/avatar.jpg",
    //collection : "/collections/iasc/collection.jpg",
    discord : "https://discord.gg/A3rmDSjBaJ",
    twitter : "https://twitter.com/ICPuppies",
    medium : "https://medium.com/@ICPuppies",
    web : "https://icpuppies.io",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress:
      "9f76290b181807c5fa3c7cfcfca2525d578a3770f40ae8b14a03a4a3530368e2",
    blurb: (
      <>ICPuppies was created with the idea of being a fun, easy-going collection that's very accessible to all newcomers to the Internet Computer NFT world. We're inspired by the retro 8-bit video game aesthetic as we feel it's appealing to people everywhere.<br /><br />Half of the initial launch profits are directed towards charities and on top of that, a portion of our resale volume goes to our partners at Infinite Charity Project, forever! 
</>
    ),
  },
  {
    canister: "ep54t-xiaaa-aaaah-qcdza-cai",
    priority : 10,
    name: "ICPuppies Wearables",
    unit : "ICPuppy Wearable",
    brief : "Wearable collection for owners of ICPuppies",
    description : "ICPuppies Wearables are accessories for your favorite puppies on the Internet Computer. We will airdrop these during limited special events or holidays.",
    route: "icpuppies-wearables",
    keywords : "puppies icpuppies nft charity 8-bit pixel dog doge puppy wearable ",
    banner : "/collections/icpuppy/banner.jpg",
    avatar : "/collections/icpuppy/avatar2.jpg",
    //collection : "/collections/iasc/collection.jpg",
    discord : "https://discord.gg/A3rmDSjBaJ",
    twitter : "https://twitter.com/ICPuppies",
    medium : "https://medium.com/@ICPuppies",
    web : "https://icpuppies.io",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress:
      "9f76290b181807c5fa3c7cfcfca2525d578a3770f40ae8b14a03a4a3530368e2",
    blurb: (
      <>These wearables will be dropped to ICPuppies holders during special events, holidays or specific occasions. The first wearable collection was dropped during Halloween, with more to come in the future.</>
    ),
  },
  {
    canister: "bxdf4-baaaa-aaaah-qaruq-cai",
    priority : 100,
    name: "ICPunks",
    unit : "ICPunk",
    brief : "10,000 ICPunks - 2nd NFT on the IC",
    route: "icpunks",
    keywords : "",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress:
      "c47942416fa8e7151f679d57a6b2d2e01a92fecd5e6f9ac99f6db548ea4f37aa",
    blurb: (
      <>
        Are you down with the clown? Get your hands on the latest NFT to hit the
        Internet Computer! You can wrap and trade them on the Marketplace!{" "}
        <strong>
          Wrapped ICPunks are 1:1 wrapped versions of actual ICPunks
        </strong>{" "}
        - you can read more about how to wrap, unwrap, and how safe it is{" "}
        <a
          href="https://medium.com/@toniqlabs/wrapped-nfts-8c91fd3a4c1"
          target="_blank"
          rel="noreferrer"
        >
          here
        </a>
      </>
    ),
  },
  {
    canister: "3db6u-aiaaa-aaaah-qbjbq-cai",
    priority : 10,
    name: "IC Drip",
    unit : "IC Drip",
    brief : "Drip on the IC",
    route: "icdrip",
    keywords : "",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.025,
    comaddress:
      "c7e461041c0c5800a56b64bb7cefc247abc0bbbb99bd46ff71c64e92d9f5c2f9",
    blurb: (
      <>
        IC Drip are randomly generated meta-commerce shopping carts for outfits
        and personas stored on chain. Stats, images, and other functionality are
        intentionally omitted for others to interpret. Feel free to use IC Drip
        in any way you want.{" "}
        <a
          href="https://dvr6e-lqaaa-aaaai-qam5a-cai.raw.ic0.app/"
          target="_blank"
          rel="noreferrer"
        >
          IC Drip Website
        </a>
      </>
    ),
  },
  {
    canister: "b5el6-hqaaa-aaaah-qcdhq-cai",
    priority : 10,
    name: "Wild and West",
    unit : "NFT",
    brief : "Collection by the Wild and West team",
    route: "wildwest",
    banner:"/banner/ww.png",
    keywords : "",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress:
      "9616e04724bd990eda94a848cbfe0dab273d6d663dee7e40e6e314fb34395dcd",
    blurb: (
      <>
        <p>Wild and West: The Journey Begins. We're excited to have you! Here are some of the amazing perks you get for participating in our pre-sale: access to the "Maverick" role in Discord along with its very own exclusive channel, daily NFT updates, and the chance to help us decide rarity. You will also be granted access to Keak the moment it launches, the chance to learn how genesis works, and any first glimpses at all future projects (collaborations and other). For more information <a href="https://t.co/v7Gy1l1ILi" target="_blank">click here</a>. We can't thank you enough for all of your support. Welcome to the Wild and West!</p>
        <strong>Important: These NFTs are placeholder NFTs, holders will receive the real Minted NFTs on December 1st. All placeholders are equal.</strong>
      </>
    ),
  },
  {
    canister: "btggw-4aaaa-aaaah-qcdgq-cai",
    priority : 10,
    name: "IC Pumpkins",
    unit : "Pumpkin",
    brief : "Halloween themed pumpkins",
    route: "icpumpkins",
    keywords : "",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress:
      "9616e04724bd990eda94a848cbfe0dab273d6d663dee7e40e6e314fb34395dcd",
    blurb: (
      <>
        <p>Halloween lovers only! ICPumpkin is 2222 unique pumpkins! The collection consists of 20 really different cool characters, each with their own mood and costume for this holiday. Halloween isn't just for candy anymore!
Specially for internet computer. Follow us on twitter: <a href="https://twitter.com/ICPumpkin" target="_blank">@ICPumpkin</a></p>
      </>
    ),
  },
  {
    canister: "73xld-saaaa-aaaah-qbjya-cai",
    priority : 10,
    name: "Wing",
    unit : "NFT",
    keywords : "",
    route: "wing",
    brief : "Photos by Oli and Wing",
    nftv : false,
    mature: true,
    market : true,
    commission: 0.025,
    comaddress:
      "1d978f4f38d19dca4218832e856c956678de0aa470cd492f5d8ac4377db6f2a2",
    blurb: (
      <>
        To escape from containment and restriction, releasing the stressors held
        so long in the body, Wings's ego is jettisoned as she explores a more
        fundamental form of existence, expressing her humanity in this elemental
        piece.
        <br />
        She is framed within the themes of air, water, to take flight on chalky
        cliff tops overlooking distant horizons, to express the existential
        freedom that lives within. No borders.
        <br />
        And so through this series I invite the viewer to celebrate their own
        sovereignty of consciousness; to be bold as we emerge from our cocoons
        and open ourselves up to the world and each other again.
      </>
    ),
  },
  {
    canister: "kss7i-hqaaa-aaaah-qbvmq-cai",
    priority : 10,
    name: "ICelebrity",
    unit : "NFT",
    brief : "100 Handrawn celeberities",
    route: "icelebrity",
    keywords : "",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.035,
    comaddress:
      "8b6840cb0e67738e69dbb6d79a3963f7bd93c35f593a393be5cc39cd59ed993e",
    blurb: false,
  },
  {
    canister: "k4qsa-4aaaa-aaaah-qbvnq-cai",
    priority : 10,
    name: "Faceted Meninas",
    unit : "NFT",
    brief : "Unique 3D Meninas",
    route: "faceted-meninas",
    keywords : "",
    nftv : false,
    mature: false,
    market : true,
    commission: 0.02,
    comaddress:
      "12692014390fbdbb2f0a1ecd440f02d29962601a782553b45bb1a744f167f13b",
    blurb: (
      <>
        Faceted Meninas is a creature species that holds the power of the
        universe to act as a magic pillar giving their allies the essence of
        outer worlds to maximize their powers.
      </>
    ),
  },
  {
    canister: "uzhxd-ziaaa-aaaah-qanaq-cai",
    priority : 10,
    name: "ICP News",
    unit : "NFT",
    brief : "Art by ICP News",
    nftv : false,
    keywords : "",
    mature: false,
    market : true,
    route: "icp-news",
    commission: 0.02,
    comaddress:
      "c7e461041c0c5800a56b64bb7cefc247abc0bbbb99bd46ff71c64e92d9f5c2f9",
    blurb: false,
  },
  {
    canister: "tde7l-3qaaa-aaaah-qansa-cai",
    priority : 10,
    name: "Cronic Wearables",
    unit : "Cronic Wearable",
    brief : "Wearables for your Cronic",
    route: "wearables",
    nftv : false,
    keywords : "",
    mature: false,
    market : true,
    commission: 0.025,
    comaddress:
      "c7e461041c0c5800a56b64bb7cefc247abc0bbbb99bd46ff71c64e92d9f5c2f9",
    blurb: false,
  },
  {
    canister: "gevsk-tqaaa-aaaah-qaoca-cai",
    priority : 10,
    name: "ICmojis",
    unit : "ICmoji",
    route: "icmojis",
    keywords : "bulls dfinity",
    banner : "/collections/icmoji/banner.png",
    avatar : "/collections/icmoji/avatar.jpg",
    collection : "/collections/icmoji/collection.jpg",
    medium : "https://medium.com/@icmojis",
    telegram : "https://t.me/icmojis",
    discord : "https://discord.gg/mu2c6SG44E",
    twitter : "https://twitter.com/icmoji",
    web : "https://icmoji.com/",
    brief : "ICmojis are playable characters in ICmoji Origins",
    nftv : false,
    mature: false,
    market : true,
    keywords : "ICmoji, ICmojis, Origins, Game, Card, Emoji, Emote, Reaction",
    commission: 0.02,
    comaddress:
      "df13f7ef228d7213c452edc3e52854bc17dd4189dfc0468d8cb77403e52b5a69",
    blurb: (<>ICmojis are playable characters in ICmoji Origins - a multiplayer strategy game built on the Internet Computer. Learn more at our <a href="https://icmoji.com/" target="_blank">website</a></>),
  },
  {
    canister: "owuqd-dyaaa-aaaah-qapxq-cai",
    priority : 10,
    name: "ICPuzzle",
    unit : "NFT",
    brief : "Find where you fit in the puzzle",
    route: "icpuzzle",
    keywords : "Puzzle Utility Game",
    banner : "/collections/puzzle/banner.jpg",
    avatar : "/collections/puzzle/avatar.jpg",
    collection : "/collections/puzzle/collection.jpg",
    twitter : "https://twitter.com/MyArtBar",
    nftv : false,
    keywords : "",
    mature: true,
    market : true,
    commission: 0.02,
    comaddress:
      "12692014390fbdbb2f0a1ecd440f02d29962601a782553b45bb1a744f167f13b",
    blurb: false,
  },
  {
    canister: "q6hjz-kyaaa-aaaah-qcama-cai",
    priority : 10,
    name: "ICPBunny",
    unit : "Bunny",
    brief : "10,000 ICBunnies on the IC",
    route: "icpbunny",
    nftv : true,
    mature: false,
    market : true,
    commission: 0.025,
    comaddress:
      "9f04077bd8ef834f7bcca5177f28fb655a7e68d8f2da9c1e6441c4f567f5dce7",
    blurb: false,
  },
  {
    canister: "eb7r3-myaaa-aaaah-qcdya-cai",
    priority : 10,
    name: "Iconic2021",
    unit : "NFT",
    brief : "The Iconic 2021 curated collection",
    route: "iconic2021",
    nftv : false,
    mature: false,
    market : true,
    keywords : "",
    commission: 0.035,
    comaddress:
      "c7e461041c0c5800a56b64bb7cefc247abc0bbbb99bd46ff71c64e92d9f5c2f9",
    blurb: false,
  },
  
  
  {
    canister: "dv6u3-vqaaa-aaaah-qcdlq-cai",
    priority : 10,
    name: "Tyler & Dakota",
    unit : "NFT",
    route: "tylerdakota",
    brief : "An Iconic 2021 Collection",
    nftv : false,
    keywords : "",
    mature: false,
    market : true,
    commission: 0.1,
    comaddress:
      "f9deb8b1752f6230f1f86c9ca0b7c613120733acadd3a3279ea843523f22d974",
    blurb: (<>Tyler and Dakota are a writer / designer team interested in semiotics and altered states. This is a video series in which common phrases become hypnotic mantras.<br /><br /><Button data-paperform-id="inconic21tylerdak" data-popup-button="1" variant="outlined" color={"primary"} style={{fontWeight:"bold", cursor:"pointer"}}>Subcribe for Updates!</Button></>),
  },
  
  {
    canister: "crt3j-mqaaa-aaaah-qcdnq-cai",
    priority : 10,
    name: "Neil White",
    unit : "NFT",
    route: "neilwhite",
    brief : "An Iconic 2021 Collection",
    nftv : false,
    keywords : "",
    mature: false,
    market : true,
    commission: 0.1,
    comaddress:
      "6d4aba3426e332add7b55d88a005805b436e98bec092f42e89510596a3ac8ee5",
    blurb: (<>Neil White is a Miami-based contemporary artist. His work focuses on ironic portraits of historical icons and social commentary in the form of robots. He employs both digital art and studio painting mediums in a hyperrealistic pop art style.<br /><br /><Button data-paperform-id="5bxwhthj" data-popup-button="1" variant="outlined" color={"primary"} style={{fontWeight:"bold", cursor:"pointer"}}>Subcribe for Updates!</Button></>),
  },
  
  {
    canister: "cnxby-3qaaa-aaaah-qcdpq-cai",
    priority : 10,
    name: "Andre Wee",
    unit : "NFT",
    route: "andrewee",
    brief : "An Iconic 2021 Collection",
    nftv : false,
    keywords : "",
    mature: false,
    market : true,
    commission: 0.1,
    comaddress:
      "ccac00c36859008eb9d33597f2c51ff8778dc4d3146d992b453eb330dee3f41c",
    blurb: (<>André Wee, a newcomer to the NFT Art scene, is an experimental illustrator that jumps between both the virtual and physical world when he creates his craft. The works that he creates blend Technology with Art as André discovers newer ways of engaging with his viewers with creative storytelling and imagery. Aside from putting pencil to paper and pushing digital paint across a virtual canvas, André also works with animated layers hidden within the physical world through Augmented reality where he embeds narratives within his illustrations.<br /><br /><Button data-paperform-id="nunweq3r" data-popup-button="1" variant="outlined" color={"primary"} style={{fontWeight:"bold", cursor:"pointer"}}>Subcribe for Updates!</Button></>),
  },
  
  {
    canister: "ludo",
    priority : 10,
    name: "Ludo",
    unit : "NFT",
    route: "ludo",
    brief : "An Iconic 2021 Collection",
    nftv : false,
    keywords : "",
    mature: false,
    market : false,
    commission: 0.1,
    comaddress:
      "60879ff49717bfef81b15288d6359a96b5705e2d3918d1f14bba1441ea84a539",
    blurb: (<>The work of Paris-based Ludo (Ludovic Vernhet) explores a world where biotechnological chimeras offer to merge plants and animals with our technological universe. Through his work, Ludo aims to reveal the opposites that cohabit our world, often taking unlikely pairings to absurd lengths. These dualities are reconciled by the artist through the creation of hybrid organisms.
Drawn with the precision of botanical illustrations, this new order of hybrid organisms is both elegant and ferocious, simple & sometimes caustic. Butterflies become brass knuckles; carnivorous plants bare rows of hunting-knife teeth; bees hover hidden behind gas masks and goggles; automatic weapons crown the head of sunflowers; human skulls cluster together like grapes.<br /><br /><strong>Art will be on sale after BTC integration</strong><br /><br /><Button data-paperform-id="iconic21ludo" data-popup-button="1" variant="outlined" color={"primary"} style={{fontWeight:"bold", cursor:"pointer"}}>Subcribe for Updates!</Button></>),
  },
  
  {
    canister: "ckwhm-wiaaa-aaaah-qcdpa-cai",
    priority : 10,
    name: "PatternBased",
    unit : "NFT",
    route: "patternbased",
    brief : "An Iconic 2021 Collection",
    nftv : false,
    mature: false,
    market : true,
    keywords : "",
    commission: 0.1,
    comaddress:
      "fa603565b08636498f83d493c33b8cab22ddeb59eae7ffde782a5f3f35634c6d",
    blurb: (<>PatternBased is a boutique creative label at the intersection of art and technology. PatternBased is Siori Kitajima and Joseph Minadeo. Siori Kitajima is a multimedia visual artist who explores complexity and abstraction through a variety of mediums: from canvas painting to coding. Joseph Minadeo is a film composer and multimedia artist inspired by nature and technology. Both are the characters in a film that the protagonist visits to accomplish a technical task: the geek helpers. As technical artists, they celebrate the potential of generative / procedural art and are currently exploring the world of decentralization including NFTs.<br /><br /><Button data-paperform-id="iconic21pattern" data-popup-button="1" variant="outlined" color={"primary"} style={{fontWeight:"bold", cursor:"pointer"}}>Subcribe for Updates!</Button></>),
  },
  
  {
    canister: "cdvmq-aaaaa-aaaah-qcdoq-cai",
    priority : 10,
    name: "Selay Karasu",
    unit : "NFT",
    route: "selaykarasu",
    brief : "An Iconic 2021 Collection",
    nftv : false,
    mature: false,
    market : true,
    keywords : "",
    commission: 0.1,
    comaddress:
      "b4e5130404276e730dbf04515621ccae616f6665a451c0ad57daa6d2c668b62e",
    blurb: (<>Selay Karasu is a multidisciplinary artist and creative director based in Istanbul.
10 years in the industry she did numerous projection mapping and public art installations. Her A/V performances were exhibited on substantial platforms around the globe such as CERN Particle Physics Laboratory, Society For Arts And Technology [SAT], MOMA NY, Burning Man Festival (USA), WIRED, Fubiz, Vimeo(Staff Pick), Prix Ars Electronica, Signal Light Festival (CZ), IX Immersion Experience Symposium (CAN).<br /><br /><Button data-paperform-id="inconic2021selay" data-popup-button="1" variant="outlined" color={"primary"} style={{fontWeight:"bold", cursor:"pointer"}}>Subcribe for Updates!</Button></>),
  },
  
  {
    canister: "ryanpgriffin",
    priority : 10,
    name: "Ryan P. Griffin",
    unit : "NFT",
    route: "ryanpgriffin",
    brief : "An Iconic 2021 Collection",
    nftv : false,
    mature: false,
    market : false,
    keywords : "",
    commission: 0.1,
    comaddress:
      "3e3dc266e28772960518ceb5a263606e0d21a2fb5ec8c68c98740ca78b1bb60a",
    blurb: (<>Ryan P. Griffin is a visual artist based out of Los Angeles, CA. Griffin uses projected light as a vehicle to activate the environment in a poetic, performative and public way.  The artist's practice incorporates drawing, painting, photography, animation and video, while extending these traditions through contemporary digital media tools to share unique experiences. The artist organizes frequent happenings thru his ongoing project at Projected Visions, using projected light to radically repurpose place.<br /><br /><strong>Art will be ready soon for minting</strong><br /><br /><Button data-paperform-id="iconic21pattern" data-popup-button="1" variant="outlined" color={"primary"} style={{fontWeight:"bold", cursor:"pointer"}}>Subcribe for Updates!</Button></>),
  },
  
  {
    canister: "chloeyeemay",
    priority : 10,
    name: "Chloe Yee May",
    unit : "NFT",
    route: "chloeyeemay",
    brief : "An Iconic 2021 Collection",
    nftv : false,
    mature: false,
    market : false,
    keywords : "",
    commission: 0.1,
    comaddress:
      "ad7027bba25b9e97a865ead26d7367de958278a0ea758d5f80f75ecf6b185516",
    blurb: (<>An illustrator, artist currently based in New York City, Chloe tackles visual storytelling through illustration with experience in branding, concept art, character design, editorial, NFTs, as well as her own private practice. She graduated with a BFA from the Rhode Island School of Design and has since been honored most recently by the Art Directors Club with a Silver Cube in their 100th Annual Awards, one of the most prestigious design accolades. She also does collaborations overseas in Asia and has had solo shows in Shanghai and Wuhan.<br /><br /><strong>Art for display only</strong></>),
  },
];
export default collections;