const {baseConfig} = require('virmator/base-configs/base-cspell.js');

module.exports = {
    ...baseConfig,
    ignorePaths: [
        ...baseConfig.ignorePaths,
        'public/',
        'src/ic/candid',
    ],
    patterns: [
        {
            name: 'address/token',
            pattern: '/\\w{5}-\\w{5}-\\w{5}-\\w{5}-\\w{3}/',
        },
    ],
    ignoreRegExpList: ['address/token'],
    words: [
        ...baseConfig.words,
        'gifshot',
        'moonwalker',
        'detailpage',
        'icapes',
        'dfinity',
        'icpunks',
        'bignumber',
        'nftlicense',
        'Secp256k1',
        'btcflower',
        'geoip',
        'magni',
        'ctype',
        'mintregister',
        'icdrip',
        'videos_that_dont_fit_in_frame',
        'subaccount',
        'icpuppy',
        'idls',
        'ictuts',
        'fontsource',
        'cachebuster',
        'nftgeek',
        'hzld',
        'dscvr',
        'infinitywallet',
        'saletype',
        'subnetwork',
        'distrikt',
        'cronics',
        'motoko',
        'DEFI',
        'permyriad',
        'clickaway',
        'favourite',
        'cronic',
        'icpledger',
        'nonfungible',
        'eyewear',
        'roboto',
        'icscan',
        'toruslabs',
        'openlogin',
        'dexie',
        'blockies',
        'blockie',
        'nftv',
        'lazyload',
        'sjcl',
        'starkbank',
        'iefix',
        'Toniq',
        'tokenid',
        'extjs',
        'entrepôt',
    ],
};
